apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - host: coaching.dev
      http:
        paths:
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/practice-plans
            pathType: Prefix
            backend:
              service:
                name: practice-plans-srv
                port:
                  number: 3000
          - path: /api/drills
            pathType: Prefix
            backend:
              service:
                name: drills-srv
                port:
                  number: 3000
